services:
  - type: web
    name: carrot-game-online
    runtime: node
    buildCommand: "npm install --omit=dev"
    startCommand: "npm start"
    plan: starter
    previews:
      generation: manual
    renderSubdomainPolicy: enabled
    envVars:
      - key: NODE_VERSION
        value: 22
